/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const DashboardLazyRouteImport = createFileRoute('/dashboard')()
const IndexLazyRouteImport = createFileRoute('/')()
const DashboardIndexLazyRouteImport = createFileRoute('/dashboard/')()
const DashboardSettingsLazyRouteImport = createFileRoute(
  '/dashboard/settings',
)()
const DashboardPaymentsLazyRouteImport = createFileRoute(
  '/dashboard/payments',
)()
const DashboardOrdersLazyRouteImport = createFileRoute('/dashboard/orders')()
const DashboardNotificationsLazyRouteImport = createFileRoute(
  '/dashboard/notifications',
)()
const DashboardInventoryLazyRouteImport = createFileRoute(
  '/dashboard/inventory',
)()
const DashboardHelpLazyRouteImport = createFileRoute('/dashboard/help')()
const DashboardDeliveriesLazyRouteImport = createFileRoute(
  '/dashboard/deliveries',
)()
const DashboardAnalyticsLazyRouteImport = createFileRoute(
  '/dashboard/analytics',
)()
const AuthResetPasswordLazyRouteImport = createFileRoute(
  '/auth/resetPassword',
)()
const AuthRegistrationLazyRouteImport = createFileRoute('/auth/registration')()
const AuthLoginLazyRouteImport = createFileRoute('/auth/login')()
const AuthForgotPasswordLazyRouteImport = createFileRoute(
  '/auth/forgotPassword',
)()

const DashboardLazyRoute = DashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const DashboardIndexLazyRoute = DashboardIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const DashboardSettingsLazyRoute = DashboardSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/settings.lazy').then((d) => d.Route),
)
const DashboardPaymentsLazyRoute = DashboardPaymentsLazyRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/payments.lazy').then((d) => d.Route),
)
const DashboardOrdersLazyRoute = DashboardOrdersLazyRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/orders.lazy').then((d) => d.Route),
)
const DashboardNotificationsLazyRoute =
  DashboardNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/notifications.lazy').then((d) => d.Route),
  )
const DashboardInventoryLazyRoute = DashboardInventoryLazyRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/inventory.lazy').then((d) => d.Route),
)
const DashboardHelpLazyRoute = DashboardHelpLazyRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/help.lazy').then((d) => d.Route),
)
const DashboardDeliveriesLazyRoute = DashboardDeliveriesLazyRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/deliveries.lazy').then((d) => d.Route),
)
const DashboardAnalyticsLazyRoute = DashboardAnalyticsLazyRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/analytics.lazy').then((d) => d.Route),
)
const AuthResetPasswordLazyRoute = AuthResetPasswordLazyRouteImport.update({
  id: '/auth/resetPassword',
  path: '/auth/resetPassword',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/resetPassword.lazy').then((d) => d.Route),
)
const AuthRegistrationLazyRoute = AuthRegistrationLazyRouteImport.update({
  id: '/auth/registration',
  path: '/auth/registration',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/registration.lazy').then((d) => d.Route),
)
const AuthLoginLazyRoute = AuthLoginLazyRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))
const AuthForgotPasswordLazyRoute = AuthForgotPasswordLazyRouteImport.update({
  id: '/auth/forgotPassword',
  path: '/auth/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/forgotPassword.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/auth/forgotPassword': typeof AuthForgotPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/registration': typeof AuthRegistrationLazyRoute
  '/auth/resetPassword': typeof AuthResetPasswordLazyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsLazyRoute
  '/dashboard/deliveries': typeof DashboardDeliveriesLazyRoute
  '/dashboard/help': typeof DashboardHelpLazyRoute
  '/dashboard/inventory': typeof DashboardInventoryLazyRoute
  '/dashboard/notifications': typeof DashboardNotificationsLazyRoute
  '/dashboard/orders': typeof DashboardOrdersLazyRoute
  '/dashboard/payments': typeof DashboardPaymentsLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/auth/forgotPassword': typeof AuthForgotPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/registration': typeof AuthRegistrationLazyRoute
  '/auth/resetPassword': typeof AuthResetPasswordLazyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsLazyRoute
  '/dashboard/deliveries': typeof DashboardDeliveriesLazyRoute
  '/dashboard/help': typeof DashboardHelpLazyRoute
  '/dashboard/inventory': typeof DashboardInventoryLazyRoute
  '/dashboard/notifications': typeof DashboardNotificationsLazyRoute
  '/dashboard/orders': typeof DashboardOrdersLazyRoute
  '/dashboard/payments': typeof DashboardPaymentsLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/auth/forgotPassword': typeof AuthForgotPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/registration': typeof AuthRegistrationLazyRoute
  '/auth/resetPassword': typeof AuthResetPasswordLazyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsLazyRoute
  '/dashboard/deliveries': typeof DashboardDeliveriesLazyRoute
  '/dashboard/help': typeof DashboardHelpLazyRoute
  '/dashboard/inventory': typeof DashboardInventoryLazyRoute
  '/dashboard/notifications': typeof DashboardNotificationsLazyRoute
  '/dashboard/orders': typeof DashboardOrdersLazyRoute
  '/dashboard/payments': typeof DashboardPaymentsLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/forgotPassword'
    | '/auth/login'
    | '/auth/registration'
    | '/auth/resetPassword'
    | '/dashboard/analytics'
    | '/dashboard/deliveries'
    | '/dashboard/help'
    | '/dashboard/inventory'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgotPassword'
    | '/auth/login'
    | '/auth/registration'
    | '/auth/resetPassword'
    | '/dashboard/analytics'
    | '/dashboard/deliveries'
    | '/dashboard/help'
    | '/dashboard/inventory'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/forgotPassword'
    | '/auth/login'
    | '/auth/registration'
    | '/auth/resetPassword'
    | '/dashboard/analytics'
    | '/dashboard/deliveries'
    | '/dashboard/help'
    | '/dashboard/inventory'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardLazyRoute: typeof DashboardLazyRouteWithChildren
  AuthForgotPasswordLazyRoute: typeof AuthForgotPasswordLazyRoute
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthRegistrationLazyRoute: typeof AuthRegistrationLazyRoute
  AuthResetPasswordLazyRoute: typeof AuthResetPasswordLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/deliveries': {
      id: '/dashboard/deliveries'
      path: '/deliveries'
      fullPath: '/dashboard/deliveries'
      preLoaderRoute: typeof DashboardDeliveriesLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/auth/resetPassword': {
      id: '/auth/resetPassword'
      path: '/auth/resetPassword'
      fullPath: '/auth/resetPassword'
      preLoaderRoute: typeof AuthResetPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/registration': {
      id: '/auth/registration'
      path: '/auth/registration'
      fullPath: '/auth/registration'
      preLoaderRoute: typeof AuthRegistrationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgotPassword': {
      id: '/auth/forgotPassword'
      path: '/auth/forgotPassword'
      fullPath: '/auth/forgotPassword'
      preLoaderRoute: typeof AuthForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardLazyRouteChildren {
  DashboardAnalyticsLazyRoute: typeof DashboardAnalyticsLazyRoute
  DashboardDeliveriesLazyRoute: typeof DashboardDeliveriesLazyRoute
  DashboardHelpLazyRoute: typeof DashboardHelpLazyRoute
  DashboardInventoryLazyRoute: typeof DashboardInventoryLazyRoute
  DashboardNotificationsLazyRoute: typeof DashboardNotificationsLazyRoute
  DashboardOrdersLazyRoute: typeof DashboardOrdersLazyRoute
  DashboardPaymentsLazyRoute: typeof DashboardPaymentsLazyRoute
  DashboardSettingsLazyRoute: typeof DashboardSettingsLazyRoute
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
}

const DashboardLazyRouteChildren: DashboardLazyRouteChildren = {
  DashboardAnalyticsLazyRoute: DashboardAnalyticsLazyRoute,
  DashboardDeliveriesLazyRoute: DashboardDeliveriesLazyRoute,
  DashboardHelpLazyRoute: DashboardHelpLazyRoute,
  DashboardInventoryLazyRoute: DashboardInventoryLazyRoute,
  DashboardNotificationsLazyRoute: DashboardNotificationsLazyRoute,
  DashboardOrdersLazyRoute: DashboardOrdersLazyRoute,
  DashboardPaymentsLazyRoute: DashboardPaymentsLazyRoute,
  DashboardSettingsLazyRoute: DashboardSettingsLazyRoute,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
}

const DashboardLazyRouteWithChildren = DashboardLazyRoute._addFileChildren(
  DashboardLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardLazyRoute: DashboardLazyRouteWithChildren,
  AuthForgotPasswordLazyRoute: AuthForgotPasswordLazyRoute,
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthRegistrationLazyRoute: AuthRegistrationLazyRoute,
  AuthResetPasswordLazyRoute: AuthResetPasswordLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
